<?php
	$termos_de_uso = '
<h3>Termos e Condições de uso</h3>

ESTES TERMOS DE USO ("TERMOS") VINCULAM VOCÊ, A EMPRESA QUE VOCÊ REPRESENTA E A EMPRESA QUE O REGISTROU (COLETIVAMENTE "VOCÊ") AOS TERMOS E CONDIÇÕES ESTABELECIDOS NESTE DOCUMENTO EM RELAÇÃO AO SEU USO DO SOFTWARE, DO SITE, DOS APLICATIVOS MÓVEIS OU DE APLICATIVOS CONECTADOS DA DidáticaOnline, INC. ("NOSSO", "NÓS", "NOS" OU "DidáticaOnline") COMO APPLE TV, SERVIÇOS OU OUTRAS OFERTAS EM NOSSO SITE (COLETIVAMENTE, NOSSOS "SERVIÇOS"). AO USAR QUALQUER UM DOS SERVIÇOS DA DidáticaOnline OU CLICAR NO BOTÃO "INSCREVER-SE", VOCÊ CONCORDA EM SE VINCULAR AOS TERMOS. SE VOCÊ NÃO CONCORDA COM TODOS ESTES TERMOS, CLIQUE NO BOTÃO "X" E NÃO UTILIZE OS SERVIÇOS DA DidáticaOnline. A ACEITAÇÃO DA DidáticaOnline ESTÁ EXPRESSAMENTE CONDICIONADA AO SEU CONSENTIMENTO PARA COM TODOS OS TERMOS, COM EXCLUSÃO DE TODOS OS OUTROS TERMOS. SE ESTES TERMOS FOREM CONSIDERADOS UMA OFERTA PELA DidáticaOnline, A ACEITAÇÃO É EXPRESSAMENTE LIMITADA A ESTES TERMOS.

Cláusula de pré-arbitragem:
IMPORTANTE: AO CONCORDAR COM ESTES TERMOS, VOCÊ CONCORDA EM RESOLVER DISPUTAS COM A DidáticaOnline POR MEIO DE UMA ARBITRAGEM VINCULATIVA (E COM EXCEÇÕES MUITO LIMITADAS, FORA DO TRIBUNAL), E RENUNCIA A DETERMINADOS DIREITOS A PARTICIPAR DE AÇÕES COLETIVAS, CONFORME DEFINIDO NA SEÇÃO 18.

Todos os termos em maiúsculas usados e não definidos de outra forma no presente documento terão o significado que lhes é atribuído na Política de Privacidade ("Política de Privacidade") e nos Termos e condições do instrutor ("Termos do Instrutor") da DidáticaOnline.

Qualquer versão destes Termos de Uso em um idioma diferente do inglês é fornecida por conveniência, e você entende e concorda que o idioma inglês terá precedência em caso de algum conflito.

2. Contratos adicionais

Quaisquer informações pessoais enviadas em relação ao Seu uso dos Serviços está sujeita à Nossa Política de Privacidade, a qual é, por este instrumento, incorporada por referência nestes Termos.

Além disso, se Você for um Instrutor (conforme definido abaixo), também está sujeito aos Termos do Instrutor, os quais são, por este instrumento, incorporados por referência nestes Termos. Se Você for Instrutor e houver um conflito entre estes Termos e os Termos do Instrutor, os Termos do Instrutor prevalecerão.

3. Disposições gerais

Nossos Serviços permitem que os alunos ("Alunos") se conectem a instrutores contratados independentes (os "Instrutores", coletivamente com Alunos, os "Usuários") que fornecem instruções ao vivo e gravadas, aulas de reforço e serviços de aprendizagem (os "Cursos") por meio dos Nossos Serviços. Os Serviços incluem, sem limitação, facilitar e hospedar Cursos e materiais de apoio, e receber feedback de Usuários.

Periodicamente, podemos atualizar estes Termos para esclarecer nossas práticas ou para refletir práticas novas ou diferentes, como quando Nós adicionamos novos recursos, e a DidáticaOnline reserva-se o direito, a seu exclusivo critério, de modificar e/ou fazer alterações nestes Termos a qualquer momento. Se Nós fizermos alguma alteração significativa nestes Termos, notificaremos Você usando meios importantes, como notificação por e-mail enviada para o endereço de e-mail especificado em Sua Conta ou publicando uma notificação em Nossos Serviços. As modificações entrarão em vigor no dia em que elas forem publicadas, salvo se indicado de outra maneira.

Seu uso contínuo dos Nossos Serviços após as alterações entrarem em vigor significa que Você aceita essas alterações. Você deve visitar os Serviços regularmente para estar ciente da última versão dos Termos, pois quaisquer Termos revisados deverão prevalecer sobre todos os Termos anteriores.

A DidáticaOnline poderá modificar os Serviços ou interromper a disponibilidade deles a qualquer momento.

Você é o único responsável pelo pagamento das contas de serviço, telefônicas, de dados e/ou de outras taxas e custos associados ao Seu acesso e uso dos Serviços, bem como pela obtenção e manutenção de todos os equipamentos telefônicos, computacionais e de outros tipos necessários para tal acesso e uso.

Se optar por acessar ou usar Nossos Serviços que envolvam pagamento de uma taxa, Você concordará em pagar e será responsável pelo pagamento dessa taxa e de todas as taxas associadas a tal acesso ou uso. Se fornecer informações de cartão de crédito para pagar tais taxas, Você, pelo presente instrumento, declara e garante que Você está autorizado a fornecer tais informações e, pelo presente instrumento, autoriza a DidáticaOnline a cobrar Seu cartão de crédito regularmente para pagar as taxas que são devidas.

Caso Seu método de pagamento falhe ou Sua Conta esteja vencida, Nós poderemos cobrar as taxas devidas usando outros mecanismos de cobrança. Isso pode incluir outros métodos de cobrança arquivados e/ou a contratação de agências de cobrança e assessoria jurídica. Também poderemos bloquear Seu acesso a quaisquer Serviços com resolução pendente de quaisquer valores devidos por Você à DidáticaOnline.

Todo o uso, acesso e outras atividades realizadas por Você relacionados aos Serviços devem estar de acordo com todas as leis e os regulamentos aplicáveis, incluindo, sem limitações, leis relativas a direitos autorais e outros usos de propriedade intelectual, e à privacidade e identidade pessoal. Além disso, é proibido o acesso aos Nossos Serviços a partir de territórios onde seu conteúdo seja ilegal. Aqueles que optarem por acessar ou utilizar os Serviços de locais fora dos Estados Unidos, farão isso por iniciativa própria e serão responsáveis pelo cumprimento de todas as normas locais, incluindo, sem limitação, as normas sobre a internet, dados, e-mail ou privacidade. Você também concorda em cumprir todas as leis aplicáveis relacionadas à transmissão de dados técnicos exportados dos Estados Unidos ou do país em que reside. Se usar os Serviços ou Plataformas de Terceiros (conforme definido na próxima seção) de países fora dos Estados Unidos, Você deve concordar em cumprir todas as normas locais relativas à conduta on-line e ao conteúdo aceitável.

4. Aviso de isenção de responsabilidade

Os Serviços são apenas um mercado para Instrutores e Alunos. Nós não contratamos ou empregamos Instrutores, nem somos responsáveis por quaisquer interações envolvidas entre os Instrutores e os Alunos que compram o Curso de um Instrutor por meio dos Serviços. Nós não nos responsabilizamoas por disputas, reivindicações, perdas, lesões ou danos de qualquer tipo que possam surgir ou estar relacionados à conduta dos Instrutores ou Alunos, incluindo, mas não limitado, à confiança de qualquer Aluno em qualquer informação fornecida por um Instrutor.

Nós não controlamos o Conteúdo Enviado (conforme definido abaixo) publicado nos Serviços e, como tal, não garantimos, de nenhuma maneira, a confiabilidade, validade, exatidão ou veracidade de tal Conteúdo Enviado. Você também confirma que, ao usar os Serviços, a DidáticaOnline pode expor Você ao Conteúdo Enviado que Você considere ofensivo, indecente ou censurável. A DidáticaOnline não se responsabiliza por evitar que esse conteúdo chegue até Você nem tem nenhuma responsabilidade por Seu acesso ou uso de qualquer Conteúdo Enviado, nos termos permitidos pela legislação em vigor.

Os Serviços podem lhe dar acesso a links para plataformas de terceiros ("Plataformas de Terceiros"), seja diretamente ou através de Cursos ou Instrutores. A DidáticaOnline não endossa quaisquer Plataformas de Terceiros e não as controla de nenhuma forma. Portanto, a DidáticaOnline não assume nenhuma responsabilidade associada a Plataformas de Terceiros. Você precisa tomar medidas adequadas para determinar se o acesso a uma Plataforma de Terceiros é apropriado, e para proteger Suas informações pessoais e Sua privacidade em tal Plataforma de Terceiros.

5. Conduta

Você só pode acessar os Serviços para fins lícitos. Você é o único responsável pelo conhecimento e pela adesão a todos e quaisquer regulamentos, leis e normas referentes a Seu uso dos Serviços. Você concorda em não usar os Serviços ou o Conteúdo da Empresa (conforme definido abaixo) para recrutar, incitar ou contatar, de qualquer forma, Instrutores ou possíveis usuários para emprego ou contratação para um negócio não afiliado Conosco sem Nossa autorização prévia por escrito, a qual pode ser recusada a Nosso exclusivo critério. Você assume todo e qualquer risco de quaisquer reuniões ou contatos entre Você e quaisquer Instrutores ou outros Usuários dos Serviços.

6. Obrigações específicas dos Instrutores

Consulte os Termos do Instrutor.

7. Obrigações específicas dos Alunos

Como Aluno, Você declara, garante e concorda que:

Leu, entendeu e aceita submeter-se às informações de preço (consulte a seção Preço, abaixo) antes de utilizar os Serviços ou registrar-se para frequentar um Curso.
Se Você for menor de 18 anos, somente usará os Serviços com a participação, supervisão e aprovação de um pai ou responsável legal. Crianças menores de 13 anos não podem cadastrar uma Conta, registrar-se ou comprar Cursos.
Você não carregará, publicará ou transmitirá, sem que seja solicitado ou autorizado, qualquer publicidade, material promocional, lixo eletrônico, spam, corrente, esquema de pirâmide ou qualquer outra forma de solicitação (comercial ou não) por meio dos Serviços.
Você não publicará ou fornecerá qualquer informação ou conteúdo inapropriado, ofensivo, racista, agressivo, sexista, pornográfico, falso, enganoso, incorreto, infrator, difamatório ou calunioso.
Você não copiará, modificará, fará engenharia reversa, reproduzirá, distribuirá, apresentará ou exibirá publicamente, comunicará ao público, criará trabalhos derivados, deformará, mutilará, invadirá o sistema operacional, interferirá ou, de outra forma, usará e explorará qualquer Conteúdo da Empresa, os Serviços ou Cursos ou Conteúdo Enviado, exceto segundo permitido por estes Termos ou pelo Instrutor relevante, conforme aplicável.
Você não enquadrará nem incorporará os Serviços para burlá-los.
Você não se passará por outra pessoa nem obterá acesso não autorizado à Conta de outra pessoa.
Você não introduzirá vírus, worm, spyware ou qualquer outro código de computador, arquivo ou programa que possa ou que se destine a danificar ou se apoderar da operação de qualquer hardware, software ou equipamento de telecomunicações, ou qualquer outro aspecto dos Serviços ou da operação do mesmo; scrape, spider, usar um robô ou outros meios automatizados de qualquer tipo para acessar os Serviços.
Você não divulgará quaisquer informações pessoais a um Instrutor, caso contrário será responsável por controlar como Suas informações pessoais são divulgadas ou usadas, o que inclui, por exemplo, tomar medidas apropriadas para proteger tais informações.
Você não solicitará informações pessoais de Instrutores ou de outros Alunos.
Os alunos entendem e concordam que os Instrutores de quem os Alunos podem ter adquirido Cursos podem optar por encerrar suas Contas com a DidáticaOnline e torná-las inativas. A DidáticaOnline não garante a disponibilidade do Instrutor para os Alunos nem será responsabilizada por quaisquer problemas relacionados à disponibilidade do Instrutor.

8. Registro

Para usar certos Serviços, Você precisará se registrar e obter uma conta e uma senha. Quando Você se registrar, as informações que Você Nos fornecer durante o processo de registro, Nos ajudarão na oferta de conteúdo, no atendimento ao cliente, na gestão de rede e em outros serviços. Você é o único responsável por manter a confidencialidade da Sua conta, do seu Nome de Usuário e da sua senha (coletivamente, Sua "Conta") e por todas as atividades associadas à Sua Conta ou que ocorram nela. Você declara e garante que as informações de Sua Conta serão sempre precisas. Você deve (a) notificar-nos imediatamente sobre qualquer uso não autorizado de Sua Conta e qualquer outra violação de segurança e (b) assegurar-se de que Você saia de Sua Conta ao final de cada utilização dos Serviços. Nos termos permitidos pela lei em vigor, não podemos e não seremos responsáveis por quaisquer perdas ou danos decorrentes da Sua falha em cumprir com os requisitos acima mencionados ou como resultado do uso de Sua Conta, seja com ou sem o Seu conhecimento, antes que Você nos notifique do acesso não autorizado à Sua Conta.

Você não pode transferir Sua Conta a qualquer outra pessoa e não pode usar a Conta de outra pessoa em nenhum momento. Nos casos em que Você tiver autorizado ou registrado outro indivíduo, incluindo um menor, para usar Sua Conta, Você será totalmente responsável (i) pela conduta on-line de tal Aluno; (ii) pelo controle do acesso do Aluno e pelo uso dos Serviços; e (iii) pelas consequências de qualquer utilização indevida.

9. Conteúdo, licenças e permissões

Todos os softwares, tecnologia, designs, materiais, informações, comunicações, textos, gráficos, links, arte eletrônica, animações, ilustrações, trabalhos de arte, clipes de áudio, videoclipes, fotos, imagens, revisões, ideias e outros dados ou materiais ou conteúdo protegidos por direitos autorais, incluindo as disposições e a seleção, são "Conteúdo". Onde a DidáticaOnline fornece Conteúdo para Você em relação aos Serviços, incluindo, dentre outros, o software, os produtos e o site, é considerado "Conteúdo da Empresa". Conteúdo carregado, transmitido ou publicado nos Serviços por um Usuário é "Conteúdo Enviado". O Conteúdo permanece como propriedade privada da pessoa ou da entidade que o fornece (ou seu afiliado e/ou provedores externos e fornecedores) e é protegido, sem limitação, nos termos das leis estrangeiras de direitos autorais e dos Estados Unidos e outras leis de propriedade intelectual. Pelo presente documento, Você declara e garante que tem todas as licenças, os direitos, os consentimentos e as permissões necessários para conceder os direitos estabelecidos nestes Termos da DidáticaOnline em relação ao Seu Conteúdo Enviado, e que a DidáticaOnline não precisará obter quaisquer licenças, direitos, consentimentos ou permissões, ou efetuar quaisquer pagamentos para qualquer terceiro por qualquer uso ou exploração do Seu Conteúdo Enviado, conforme autorizado nestes Termos. Ela também não terá qualquer responsabilidade por Você ou qualquer terceiro como resultado de qualquer uso ou exploração do Seu Conteúdo Enviado, conforme autorizado nestes Termos.

A DidáticaOnline, por meio deste instrumento, concede a Você (como Usuário) uma licença limitada, não exclusiva, não transferível para acessar e usar Conteúdo Enviado e Conteúdo da Empresa, pelos quais Você pagou todas as taxas necessárias, exclusivamente para Seus fins pessoais, não comerciais, educacionais por meio dos Serviços, de acordo com estes Termos e quaisquer condições ou restrições associadas a Cursos ou Serviços específicos. Todos os outros usos serão expressamente proibidos sem Nosso expresso consentimento por escrito. Você não pode reproduzir, redistribuir, difundir, atribuir, vender, transmitir, alugar, compartilhar, emprestar, modificar, adaptar, editar, criar trabalhos derivados, licenciar ou transferir ou usar qualquer Conteúdo Enviado ou Conteúdo da Empresa a não ser que Nós forneçamos a Você permissão expressa para tal. O Conteúdo Enviado e o Conteúdo da Empresa são licenciados, e não vendidos, a Você. Os Instrutores não podem conceder a Você direitos de licença para o Conteúdo Enviado que Você acessa ou adquire por meio dos Serviços e qualquer licença direta é nula e uma violação destes Termos.

Não obstante o supracitado, reservamo-nos o direito de revogar esta licença para acessar e usar o Conteúdo Enviado e o Conteúdo da Empresa concedido a Você como descrito acima, conforme detalhado na seção 15 abaixo.

A DidáticaOnline RESPEITA TODAS AS LEIS DE DIREITOS AUTORAIS, PRIVACIDADE, DIFAMAÇÃO E OUTRAS LEIS RELATIVAS A CONTEÚDO E INFORMAÇÕES E NÃO TOLERARÁ A VIOLAÇÃO DE TAIS LEIS. NÃO OBSTANTE O REFERIDO ANTERIORMENTE, A DidáticaOnline NÃO INVESTIGA O CONTEÚDO ENVIADO E TODO O USO DO CONTEÚDO ENVIADO FEITO POR VOCÊ É POR SUA CONTA E RISCO, E A DidáticaOnline NÃO TEM RESPONSABILIDADE POR TAL USO. EM ESPECIAL, NENHUMA REVISÃO OU PUBLICAÇÃO OU APARÊNCIA DO CONTEÚDO ENVIADO NOS SERVIÇOS OU POR MEIO DOS SERVIÇOS DESTINA-SE A AGIR COMO ENDOSSO OU REPRESENTAÇÃO DE QUE QUALQUER CONTEÚDO ENVIADO É LIVRE DE VIOLAÇÃO DE QUAISQUER LEIS DE DIREITOS AUTORAIS, PRIVACIDADE OU OUTRAS LEIS OU SERVIRÁ A UM PROPÓSITO PARTICULAR OU SERÁ EXATA OU ÚTIL. Se Você acredita que Seu Conteúdo Enviado viola qualquer lei ou regulamento ou é impreciso ou representa qualquer risco para um terceiro, é Sua responsabilidade tomar as providências necessárias para corrigir a situação. Se Você acredita que o Conteúdo Enviado por um terceiro ou qualquer Conteúdo da Empresa viole quaisquer leis ou regulamentos, incluindo, sem limitação, quaisquer leis de direitos autorais, Você deve informar isso à DidáticaOnline de acordo com os procedimentos que Nós mantemos em Nossa Política de Propriedade Intelectual.

Todos os direitos não expressamente concedidos nestes Termos são retidos pelos proprietários do Conteúdo, e estes Termos não concedem quaisquer licenças implícitas.

Você pode decidir nos enviar ideias não solicitadas, incluindo ideias para novas promoções, produtos, serviços, aplicativos, tecnologias ou processos ou outras ideias (coletivamente, "Ideias do Usuário"). Você não deve transmitir nenhuma Ideia do Usuário para ou por meio dos Serviços ou de Plataformas de Terceiros, ou para Nós por meio de e-mail, que Você considere confidenciais ou proprietárias. Você concorda que não seremos obrigados a tratar todas as Ideias do Usuário como sendo confidenciais ou proprietárias. Você é responsável por qualquer Ideia do Usuário que enviar. Você concorda que ao enviar Ideias do Usuário para Nós, incluindo qualquer conceito, know-how ou ideia, Você concede a Nós por meio do presente instrumento uma licença perpétua, mundial, não exclusiva, isenta de royalties, sublicenciável e transferível para usar, reproduzir, distribuir, vender, explorar, preparar trabalhos derivados e exibir as Ideias do Usuário em conexão com os Serviços, e para os negócios da DidáticaOnline (e de seu sucessor), inclusive, dentre outros, para a promoção e a redistribuição parcial ou total das Ideias do Usuário (e trabalhos derivados das mesmas) em qualquer formato de mídia e por meio de qualquer canal de mídia, seja ele conhecido atualmente ou desenvolvido no futuro, sem pagamento ou prestação de contas para Você ou outras pessoas. Nós não temos a obrigação de avaliar, analisar ou usar qualquer Ideia do Usuário.




	';